sudo: required
services:
  - docker
language: bash
env:
  global:
    - secure: "tYzjoqiqPFLhEGOW7AMeImepOJrIJ8IgskZZTDZidi4yNbicN67FrBntRRJAuk6y0JJ3RQXeQqWggnujsxeOrPnflFUpC6uSpH42IPGPcCXpA/a/oH1vNSOhN8MpAw7+vND9FTpcp+idgeC4noy2uPRVA3DE3JJuWxC+emPz9ErE/ObsPrIfhvVK2jEmn6getv46/cDIvTw7FzpjooxpoSpffHwgO91Ry88SeUrc6VWw1KsghASmoGwAez0wCZHFn0eQfa5nSuqfeLfqXVEgf7YQJ3gNOQhiBU8nwhqzXNZgyCGTb9+mvQtM2oju8STkyVFcIQJhpQIJcXtEuBqtr8mn5LxLaIOcd4rOZxOrqYwTxA0DafHqGIAlgQoO/Nyw07jjaocmJ68EO6p8RC50JIlQkg52PUEOklujpSyFhQ/M8/mWlvGsliV2DAawb1mfRyvS8huFAREDTfSteIyrZiS3fWHDmBjUgJHRhAXc0aMWQ+fxLcSdXrowe9hTuvDGzllnqWpSt6BejT8/o3N+5WmAqEJM91k5TWsSVZj1w7zLRqjVDeyBirkeMcZf2+xrUdJNFvlY6gBz0bN4msUEqZQcoa4IzX9+BPDC7cwaWEhvoD9WzgSTeLrDGyWoEmLIzzDoMnXHY3eCdo1JVKd4UdGN+6+dGHxOLLeholX2FtY="
    - secure: "s6kBp0yi+RwiF0Qrmmq89EkpOXLOQo9B6drs4QJ3+yYkdZsJDMLHIJ7E9G80V9LcuP0ykuwtZctFHgKtgsnNYN+A33Lk+c7CcH7mBc1SQADdIkD3CHX4xilyMBzGADtQWqBwnnzAyWPRidIfozYMHup/OYIABKaudvIXPUcznzGA/KLQSOEXQcOjff06SblLBvtwzGGPvyQa3a0QrPRFTtAwLjW/SP11v/Nk1ZChr9gCMfAmsmzwVxzSzlauatdKCsdjhEwJ2hN3MqICpwS/IlvC4gjx0H1C0JboX1EXv+6aOMSjJ5FqU3t5ZNwNqkDGshgxlmq2p3+KkX/wx5si5h4/8wZF+gDwfKXCCDobGxUbtYL4Fps9sP3bOSWUJY1kqRShu1rsHrlF6qCO9iahZJdM2G/2ONeRSn9jnTi9Ws2VEMWokDSp85d8olHMbWAukxR+DneV78srZaAtSRutH1jIkYDRKmww4rR1L3ouwhixreMEp33912Ia6shR6sakc24P6ZLBAlyNNEBwa00GergHuPXVrS9x6kPLsjrkV5jb5lOZx0EwEQQFtcBO1NrI737s+obs1htAA9prNTbgs5172ucShyNwpZY6bgCBmHWCFybJC5x10gZUpst4ZInHeRgTuoyce2Cyocg+hKP7R8MiTqPIJTSaSqxq8gQBqII="
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t champain/latin_squares .
  - docker run -e "BUILD_TESTING=BUILD" champain/latin_squares 3 https://hooks.slack.com/services/nottheapikey
after_success:
  - > 
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
          docker tag champain/latin_squares champain/latin_squares:latest
          docker push champain/latin_squares:latest
          docker push champain/latin_squares
      fi 
